### ISSUE TITLE
Support for graphql Version 3.x STANDARD

### ISSUE THREAD

**Issue by rheid** [seekdavidlee/Eklee-Azure-Functions-GraphQl#57]
Hello DAVID, 
thanks for the nice software you developed. 
Do you plan to include the new version of graphql in this software?

https://github.com/graphql-dotnet/graphql-dotnet/releases

**Comment by seekdavidlee** [comment]
Hi @rheid - Yes, I will be updating it shortly. I have been trying to get devops setup for the past few weeks, hence the delay.

**Comment by rheid** [comment]
That sounds really good. Many thanks! Especially the .NET version can increase. I did some fixes and extensions in the COSMOS DB part. If you are interested we can exchange ideas. Maybe you want to take them over.

**Comment by seekdavidlee** [comment]
The upgrade did not go as smoothly as I thought. There's breaking change in how [Connection Builder works](https://graphql-dotnet.github.io/docs/migrations/migration3#connection-builders): . It appears it is now designed to take in only a single type which is a breaking behavior because I use a generic type. In short, please feel free to submit a PR/idea, but I am focused on this particular issue.

**Comment by rheid** [comment]
Thanks for the quick feedback.I keep my fingers crossed that the upgrade goes well. I will wait for your update and send you the small changes I made as a Pull request.

**Comment by seekdavidlee** [comment]
The upgrade has completed and a new version has been released. I wasn't able to fix paging due to the breaking change mentioned and will be reviewing your PR shortly. Thanks!
